export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTICLES_REQUEST';
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTICLES_SUCCESS';
export const FETCH_ALL_ARTICLES_ERROR = 'FETCH_ALL_ARTICLES_ERROR';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';

export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';

export const VOTE_ARTICLE_REQUEST = 'VOTE_ARTICLE_REQUEST';
export const VOTE_ARTICLE_SUCCESS = 'VOTE_ARTICLE_SUCCESS';
export const VOTE_ARTICLE_ERROR = 'VOTE_ARTICLE_ERROR';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';